call plug#begin('~/.vim/plugged')
" General
Plug 'itchyny/lightline.vim'
Plug 'ap/vim-buftabline'
Plug 'Yggdroot/indentLine'
Plug 'jiangmiao/auto-pairs'
Plug 'tomtom/tcomment_vim'
Plug 'easymotion/vim-easymotion'
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tomtom/tlib_vim'
Plug 'bkad/CamelCaseMotion'
Plug 'junegunn/vim-slash'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tpope/vim-unimpaired'
Plug 'svermeulen/vim-easyclip'
Plug 'scrooloose/nerdtree'

" Linter
Plug 'editorconfig/editorconfig-vim'

" Theme
Plug 'nightsense/stellarized'

" Markdown
Plug 'suan/vim-instant-markdown', {'for': 'markdown'}

" Git
Plug 'airblade/vim-gitgutter'

" HTML
Plug 'mattn/emmet-vim', {'for': ['vue', 'html']}
Plug 'gregsexton/matchtag'

" CSS
Plug 'cakebaker/scss-syntax.vim', {'for': ['vue', 'scss']}
Plug 'ap/vim-css-color'

" Javascript
Plug 'posva/vim-vue', {'for': 'vue'}
Plug 'pangloss/vim-javascript', {'for': 'javascript'}
call plug#end()

set rtp+=~/.fzf

set nocompatible

" general settings
filetype on
filetype plugin indent on
syntax on

" Encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set ttyfast

" Fix backspace indent
set backspace=indent,eol,start

" Indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set smarttab
set expandtab
set autoindent
set smartindent
set smartcase

" Searching
set incsearch
set hlsearch
set ic

" Directories for wap files
set nobackup
set noswapfile

set showcmd
set clipboard=unnamed
set number
set cursorline
set ruler
set t_Co=256
set autochdir
set autoread

" Buffer
set nostartofline

" Autocomplete
set completeopt=longest,menuone

" Performance
set lazyredraw
set hidden
set re=1

" Command complete menu
set wildmenu

set termguicolors
if &term =~# '^screen'
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" add silent! to prevent show error message when colorscheme is not yet installed.
silent! colorscheme stellarized

packadd! matchit

augroup vueSyntax
    autocmd!
    " autocmd BufRead,BufNewFile *.vue set filetype=vue
    autocmd BufEnter * :syntax sync fromstart
augroup END

if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif


" Dictionary {
    set complete+=k
    set iskeyword+=-
    autocmd FileType * call s:setDict()
    function! s:setDict()
        let dict = '~/.vim/dict/'
        let type = expand('%:r:e')
        let current_filetype = &filetype
        if current_filetype == "vue"
            exe 'set dictionary+='.dict.'css.txt' |
            exe 'set dictionary+='.dict.'html.txt' |
            exe 'set dictionary+='.dict.'javascript.txt'
        else
            if current_filetype == "javascript" && type == "spec"
                exe 'set dictionary+='.dict.'vue-test-utils.txt' |
                exe 'set dictionary+='.dict.'jest.txt'
                exe 'set dictionary+='.dict.'javascript.txt'
            else
                let filepath = dict.current_filetype.'.txt'
                if !empty(glob(filepath))
                    exe 'set dictionary+='.dict.current_filetype.'.txt'
                endif
            endif
        endif
    endfunction
"}

" lightline {
    set laststatus=2
    let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
        \ 'left': [ [ 'mode', 'paste' ],
        \           [ 'readonly', 'absolutepath', 'modified' ] ],
        \ }
        \ }
"}

" t-comment {
    noremap <c-/> <c-_>
"}

" indentLine {
    let g:indentLine_concealcursor = 'inc'
    let g:indentLine_conceallevel = 2
"}

" learder {
    let mapleader=","
    let g:mapleader=","
"}

" basic {
    " :W sudo save the file
    command! W w !sudo tee % > /dev/null
    " close all open files
    command! Q qall
"}

" NerdTree {
    nnoremap <leader>a :NERDTreeToggle<CR>
" }

" emmet {
    autocmd FileType vue,html,js imap <expr> <C-e> emmet#expandAbbrIntelligent("\<tab>")
    let g:use_emmet_complete_tag = 1
"}

" ultisnips {
    let g:UltiSnipsExpandTrigger="<Tab>"
    let g:UltiSnipsJumpForwardTrigger="<C-n>"
    let g:UltiSnipsJumpBackwardTrigger="<C-p>"
"}

" CamelCaseMotion {
    map <silent> w <Plug>CamelCaseMotion_w
    map <silent> b <Plug>CamelCaseMotion_b
    map <silent> e <Plug>CamelCaseMotion_e
    map <silent> ge <Plug>CamelCaseMotion_ge
    omap <silent> iw <Plug>CamelCaseMotion_iw
    xmap <silent> iw <Plug>CamelCaseMotion_iw
    omap <silent> ib <Plug>CamelCaseMotion_ib
    xmap <silent> ib <Plug>CamelCaseMotion_ib
    omap <silent> ie <Plug>CamelCaseMotion_ie
    xmap <silent> ie <Plug>CamelCaseMotion_ie
    sunmap w
    sunmap b
    sunmap e
    sunmap ge
"}

" fzf {
    function! s:find_git_root()
        return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
    endfunction

    command! ProjectFiles execute 'Files' s:find_git_root()

    nnoremap <c-p> :ProjectFiles<CR>
"}

" buffer {
    " navigation
    nmap <leader>b :bp<CR>
    nmap <leader>f :bn<CR>
    " buffer list
    nmap <leader>l :ls<CR>
    " delete buffer
    nmap <leader>d :bd<CR>
    nmap <leader>da :bufdo bd<CR>
    " open new buffer
    nmap <leader>v :vsplit<CR>
    nmap <leader>s :split<CR>
    nmap <leader>o <C-w>o

    " resize
    if bufwinnr(1)
    map + <C-W>+
    map - <C-W>-
    endif
"}

" buftabline {
    let g:buftabline_numbers = 2
    let g:buftabline_indicators = 1
    " mapping
    nmap <leader>1 <Plug>BufTabLine.Go(1)
    nmap <leader>2 <Plug>BufTabLine.Go(2)
    nmap <leader>3 <Plug>BufTabLine.Go(3)
    nmap <leader>4 <Plug>BufTabLine.Go(4)
    nmap <leader>5 <Plug>BufTabLine.Go(5)
    nmap <leader>6 <Plug>BufTabLine.Go(6)
    nmap <leader>7 <Plug>BufTabLine.Go(7)
    nmap <leader>8 <Plug>BufTabLine.Go(8)
    nmap <leader>9 <Plug>BufTabLine.Go(9)
    nmap <leader>0 <Plug>BufTabLine.Go(10)
    " color scheme
    hi BufTabLineCurrent ctermfg=50
    hi BufTabLineHidden ctermfg=67
    hi BufTabLineActive ctermfg=97
"}

" window {
    nnoremap <C-h> <C-w>h
    nnoremap <C-j> <C-w>j
    nnoremap <C-k> <C-w>k
    nnoremap <C-l> <C-w>l
"}

" easyclip {
    let g:EasyClipUseSubstituteDefaults = 1
"}

" use j and k choose complete
inoremap <expr> j pumvisible() ? '<C-n>' : 'j'
inoremap <expr> k pumvisible() ? '<C-p>' : 'k'

" use <c-n>、<c-p> choose command history
cnoremap <C-n> <down>
cnoremap <C-p> <up>

" don't lose selection when shifting sidewards
xnoremap < <gv
xnoremap > >gv

" bracketed paste mode (valid in tmux)
if has('patch-8.0.0238')
    if &term =~ "screen"
        let &t_BE = "\e[?2004h"
        let &t_BD = "\e[?2004l"
        exec "set t_PS=\e[200~"
        exec "set t_PE=\e[201~"
    endif
else
    if has('patch-8.0.0210')
        set t_BE=
    endif

    if &term =~ "xterm" || &term =~ "screen"
        function XTermPasteBegin(ret)
            set paste
            set pastetoggle=<Esc>[201~
            return a:ret
        endfunction

        let &t_ti .= "\e[?2004h"
        let &t_te .= "\e[?2004l"

        noremap <special> <expr> <Esc>[200~ XTermPasteBegin("0i")
        inoremap <special> <expr> <Esc>[200~ XTermPasteBegin("")
        vnoremap <special> <expr> <Esc>[200~ XTermPasteBegin("c")
        cnoremap <special> <Esc>[200~ <nop>
        cnoremap <special> <Esc>[201~ <nop>
    endif
endif

" Fix matchparen plugin slow {
    let g:matchparen_timeout = 20
    let g:matchparen_insert_timeout = 20
"}

" autochdir {
    "autochdir for some plugins
    "This command makes fzf open multiple files can't work as expected.
    " autocmd BufEnter * silent! lcd %:p:h
    "command for quick directory change
    nnoremap <leader>cd :cd %:p:h<CR>:pwd<CR>
" }

" vim-instant-markdown {
    let g:instant_markdown_autostart = 0
    nnoremap <leader>md :InstantMarkdownPreview<CR>
" }

" sql.vim {
    " Disabled sql.vim mapping
    let g:omni_sql_no_default_maps = 1
" }

" remap ESC
inoremap <c-c> <ESC>
