# ~/.zshrc
alias web="~/Documents/Website"
alias down="~/Downloads"
alias cloud="~/iCloud"
alias dev="ssh walker"
alias ez="exec zsh -l"
alias box="~/Dropbox"

# git alias
alias gs="git status"
alias gc="git commit --verbose"
alias gp="git push"
alias gl="git pull"
alias gb="git branch"
alias gco="git checkout"
alias gia="git add ."
alias gm="git merge"
alias gd="git diff"
alias gr="git rebase"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias gri="git rebase --interactive"
alias grs="git rebase --skip"
alias gsh="git stash"

# kubernetes alias
source ~/Documents/Website/dotfiles/zsh/kube-alias.sh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

source ~/z.sh

# Change FZF_DEFAULT_COMMAND for finding hidden files
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

# Change default editor
export VISUAL=vim
export EDITOR="$VISUAL"

[[ -s "/Users/walkerho/.gvm/scripts/gvm" ]] && source "/Users/walkerho/.gvm/scripts/gvm"
