# ~/.zshrc
alias down="~/Downloads"
alias wa="~/Walker"
alias ez="exec zsh -l"
alias in="~/Interlnkd"
alias sail="vendor/bin/sail"
alias sa="sail artisan"

# git alias
alias gs="git status"
alias gc="git commit --verbose"
alias gp="git push"
alias gl="git pull"
alias gb="git branch"
alias gco="git checkout"
alias gia="git add ."
alias gm="git merge"
alias gd="git diff"
alias gr="git rebase"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias gri="git rebase --interactive"
alias grs="git rebase --skip"
alias gsh="git stash"
alias gshp="git stash pop"

# Vapor
alias vapor="php ~/.composer/vendor/bin/vapor"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

source ~/z.sh

# Change FZF_DEFAULT_COMMAND for finding hidden files
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

export PATH="/opt/homebrew/opt/php@8.2/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.2/sbin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi

eval "$(zoxide init zsh)"
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8