name: GitHub Actions B Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_run:
    workflows: ["Github Actions A Demo"]
    types:
      - completed
    branches: [ master ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.workflow_run.conclusion }}